export const GitlabURLs = {
    PROJECTS: 'api/v4/projects?membership=true&min_access_level=20&per_page=5',
    PROJECT_README: (projectID) => `api/v4/projects/${projectID}/repository/files/README.md/raw`,
    PROJECTS_PAGE: (page) => `api/v4/projects?membership=true&min_access_level=20&per_page=5&page=${page}`,
    PROJECT_SEARCH: (param) => `api/v4/projects?membership=true&min_access_level=20&search=${param}`,

    PROJECT_ISSUES: (projectID) => `api/v4/projects/${projectID}/issues?scope=all&with_labels_details=true&per_page=7`,
    PROJECT_ISSUES_OPENED: (projectID) => `api/v4/projects/${projectID}/issues?scope=all&state=opened&with_labels_details=true&per_page=7`,
    PROJECT_ISSUES_CLOSED: (projectID) => `api/v4/projects/${projectID}/issues?scope=all&state=closed&with_labels_details=true&per_page=7`,
    PROJECT_ISSUES_PAGE: (projectID, page) => `api/v4/projects/${projectID}/issues?scope=all&with_labels_details=true&per_page=7&page=${page}`,
    PROJECT_ISSUES_PAGE_OPENED: (projectID, page) => `api/v4/projects/${projectID}/issues?state=opened&scope=all&with_labels_details=true&per_page=7&page=${page}`,
    PROJECT_ISSUES_PAGE_CLOSED: (projectID, page) => `api/v4/projects/${projectID}/issues?state=closed&scope=all&with_labels_details=true&per_page=7&page=${page}`,
    PROJECT_ISSUES_SEARCH: (projectID, param) => `api/v4/projects/${projectID}/issues?scope=all&with_labels_details=true&search=${param}&per_page=7`,
    PROJECT_ISSUES_SEARCH_OPENED: (projectID, param) => `api/v4/projects/${projectID}/issues?state=opened&scope=all&with_labels_details=true&search=${param}&per_page=7`,
    PROJECT_ISSUES_SEARCH_CLOSED: (projectID, param) => `api/v4/projects/${projectID}/issues?state=closed&scope=all&with_labels_details=true&search=${param}&per_page=7`,

    PROJECT_MERGE_REQUESTS: (projectID) => `api/v4/projects/${projectID}/merge_requests?scope=all&state=opened&per_page=7`,
    PROJECT_MERGE_REQUESTS_OPENED: (projectID) => `api/v4/projects/${projectID}/merge_requests?state=opened&scope=all&with_labels_details=true&per_page=7`,
    PROJECT_MERGE_REQUESTS_CLOSED: (projectID) => `api/v4/projects/${projectID}/merge_requests?state=closed&scope=all&with_labels_details=true&per_page=7`,
    PROJECT_MERGE_REQUESTS_MERGED: (projectID) => `api/v4/projects/${projectID}/merge_requests?state=merged&scope=all&with_labels_details=true&per_page=7`,
    PROJECT_MERGE_REQUESTS_SEARCH_OPENED: (projectID, searchParam) => `api/v4/projects/${projectID}/merge_requests?state=opened&scope=all&with_labels_details=true&search=${searchParam}&per_page=7`,
    PROJECT_MERGE_REQUESTS_SEARCH_CLOSED: (projectID, searchParam) => `api/v4/projects/${projectID}/merge_requests?state=closed&scope=all&with_labels_details=true&search=${searchParam}&per_page=7`,
    PROJECT_MERGE_REQUESTS_SEARCH_MERGED: (projectID, searchParam) => `api/v4/projects/${projectID}/merge_requests?state=merged&scope=all&with_labels_details=true&search=${searchParam}&per_page=7`,
    PROJECT_MERGE_REQUESTS_PAGE_OPENED: (projectID, page) => `api/v4/projects/${projectID}/merge_requests?state=opened&scope=all&with_labels_details=true&per_page=7&page=${page}`,
    PROJECT_MERGE_REQUESTS_PAGE_CLOSED: (projectID, page) => `api/v4/projects/${projectID}/merge_requests?state=closed&scope=all&with_labels_details=true&per_page=7&page=${page}`,
    PROJECT_MERGE_REQUESTS_PAGE_MERGED: (projectID, page) => `api/v4/projects/${projectID}/merge_requests?state=merged&scope=all&with_labels_details=true&per_page=7&page=${page}`,

    PROJECT_MERGE_REVIEWS: (projectID, userId) => `api/v4/projects/${projectID}/merge_requests?reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&per_page=7`,
    PROJECT_MERGE_REVIEWS_OPENED: (projectID, userId) => `api/v4/projects/${projectID}/merge_requests?state=opened&reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&per_page=7`,
    PROJECT_MERGE_REVIEWS_CLOSED: (projectID, userId) => `api/v4/projects/${projectID}/merge_requests?state=closed&reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&per_page=7`,
    PROJECT_MERGE_REVIEWS_MERGED: (projectID, userId) => `api/v4/projects/${projectID}/merge_requests?state=merged&reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&per_page=7`,
    PROJECT_MERGE_REVIEWS_SEARCH: (projectID, param, userId) => `api/v4/projects/${projectID}/merge_requests?reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&search=${param}&per_page=7`,
    PROJECT_MERGE_REVIEWS_SEARCH_OPENED: (projectID, userId, param) => `api/v4/projects/${projectID}/merge_requests?state=opened&reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&search=${param}&per_page=7`,
    PROJECT_MERGE_REVIEWS_SEARCH_CLOSED: (projectID, userId, param) => `api/v4/projects/${projectID}/merge_requests?state=closed&reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&search=${param}&per_page=7`,
    PROJECT_MERGE_REVIEWS_SEARCH_MERGED: (projectID, userId, param) => `api/v4/projects/${projectID}/merge_requests?state=merged&reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&search=${param}&per_page=7`,
    PROJECT_MERGE_REVIEWS_PAGE: (projectID, userId, page) => `api/v4/projects/${projectID}/merge_requests?reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&per_page=7&page=${page}`,
    PROJECT_MERGE_REVIEWS_PAGE_OPENED: (projectID, userId, page) => `api/v4/projects/${projectID}/merge_requests?state=opened&reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&per_page=7&page=${page}`,
    PROJECT_MERGE_REVIEWS_PAGE_CLOSED: (projectID, userId, page) => `api/v4/projects/${projectID}/merge_requests?state=closed&reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&per_page=7&page=${page}`,
    PROJECT_MERGE_REVIEWS_PAGE_MERGED: (projectID, userId, page) => `api/v4/projects/${projectID}/merge_requests?state=merged&reviewer_id=${userId}&scope=assigned_to_me&with_labels_details=true&per_page=7&page=${page}`,

    MERGE_REQUEST: (projectID, mergeID) => `api/v4/projects/${projectID}/merge_requests/${mergeID}?with_labels_details=true`,
    MERGE_REQUESTS: 'api/v4/merge_requests?scope=assigned_to_me&with_labels_details=true&per_page=7',
    MERGE_REQUESTS_OPENED: 'api/v4/merge_requests?scope=assigned_to_me&state=opened&with_labels_details=true&per_page=7',
    MERGE_REQUESTS_CLOSED: 'api/v4/merge_requests?scope=assigned_to_me&state=closed&with_labels_details=true&per_page=7',
    MERGE_REQUESTS_MERGED: 'api/v4/merge_requests?scope=assigned_to_me&state=merged&with_labels_details=true&per_page=7',
    MERGE_REQUEST_SEARCH: (param) => `api/v4/merge_requests?scope=assigned_to_me&with_labels_details=true&search=${param}&per_page=7`,
    MERGE_REQUEST_SEARCH_OPENED: (param) => `api/v4/merge_requests?state=opened&scope=assigned_to_me&with_labels_details=true&search=${param}&per_page=7`,
    MERGE_REQUEST_SEARCH_CLOSED: (param) => `api/v4/merge_requests?state=closed&scope=assigned_to_me&with_labels_details=true&search=${param}&per_page=7`,
    MERGE_REQUEST_SEARCH_MERGED: (param) => `api/v4/merge_requests?state=merged&scope=assigned_to_me&with_labels_details=true&search=${param}&per_page=7`,
    MERGE_REQUEST_PAGE: (page) => `api/v4/merge_requests?scope=assigned_to_me&with_labels_details=true&per_page=7&page=${page}`,
    MERGE_REQUEST_PAGE_OPENED: (page) => `api/v4/merge_requests?state=opened&scope=assigned_to_me&with_labels_details=true&per_page=7&page=${page}`,
    MERGE_REQUEST_PAGE_CLOSED: (page) => `api/v4/merge_requests?state=closed&scope=assigned_to_me&with_labels_details=true&per_page=7&page=${page}`,
    MERGE_REQUEST_PAGE_MERGED: (page) => `api/v4/merge_requests?state=merged&scope=assigned_to_me&with_labels_details=true&per_page=7&page=${page}`,


    MERGE_REVIEWS: (userId) => `api/v4/merge_requests?reviewer_id=${userId}&scope=all&with_labels_details=true&per_page=7`,
    MERGE_REVIEWS_OPENED: (userId) => `api/v4/merge_requests?state=opened&reviewer_id=${userId}&scope=all&with_labels_details=true&per_page=7`,
    MERGE_REVIEWS_CLOSED: (userId) => `api/v4/merge_requests?state=closed&reviewer_id=${userId}&scope=all&with_labels_details=true&per_page=7`,
    MERGE_REVIEWS_MERGED: (userId) => `api/v4/merge_requests?state=merged&reviewer_id=${userId}&scope=all&with_labels_details=true&per_page=7`,
    MERGE_REVIEWS_SEARCH: (userId,param) => `api/v4/merge_requests?&reviewer_id=${userId}&scope=all&with_labels_details=true&search=${param}&per_page=7`,
    MERGE_REVIEWS_SEARCH_OPENED: (userId,param) => `api/v4/merge_requests?state=opened&reviewer_id=${userId}&scope=all&with_labels_details=true&search=${param}&per_page=7`,
    MERGE_REVIEWS_SEARCH_CLOSED: (userId,param) => `api/v4/merge_requests?state=closed&reviewer_id=${userId}&scope=all&with_labels_details=true&search=${param}&per_page=7`,
    MERGE_REVIEWS_SEARCH_MERGED: (userId,param) => `api/v4/merge_requests?state=merged&reviewer_id=${userId}&scope=all&with_labels_details=true&search=${param}&per_page=7`,
    MERGE_REVIEWS_PAGE: (userId,page) => `api/v4/merge_requests?reviewer_id=${userId}&scope=all&with_labels_details=true&per_page=7&page=${page}`,
    MERGE_REVIEWS_PAGE_OPENED: (userId,page) => `api/v4/merge_requests?state=opened&reviewer_id=${userId}&scope=all&with_labels_details=true&per_page=7&page=${page}`,
    MERGE_REVIEWS_PAGE_CLOSED: (userId,page) => `api/v4/merge_requests?state=closed&reviewer_id=${userId}&scope=all&with_labels_details=true&per_page=7&page=${page}`,
    MERGE_REVIEWS_PAGE_MERGED: (userId,page) => `api/v4/merge_requests?state=merged&reviewer_id=${userId}&scope=all&with_labels_details=true&per_page=7&page=${page}`,


    MERGE_NOTES_SORTED: (projectID, mergeID) => `api/v4/projects/${projectID}/merge_requests/${mergeID}/notes?sort=asc&order_by=updated_at`,

    ISSUES_OPENED: 'api/v4/issues?state=opened&scope=assigned_to_me&with_labels_details=true&per_page=7',
    ISSUES_CLOSED: 'api/v4/issues?state=closed&scope=assigned_to_me&with_labels_details=true&per_page=7',
    ISSUES: 'api/v4/issues?scope=assigned_to_me&with_labels_details=true&per_page=7',
    ISSUE: (projectID, issueID) => `api/v4/projects/${projectID}/issues/${issueID}?with_labels_details=true`,
    ISSUES_PAGE: (page) => `api/v4/issues?scope=assigned_to_me&with_labels_details=true&per_page=7&page=${page}`,
    ISSUES_PAGE_OPENED: (page) => `api/v4/issues?state=opened&scope=assigned_to_me&with_labels_details=true&per_page=7&page=${page}`,
    ISSUES_PAGE_CLOSED: (page) => `api/v4/issues?state=closed&scope=assigned_to_me&with_labels_details=true&per_page=7&page=${page}`,
    ISSUES_SEARCH: (param) => `api/v4/issues?scope=assigned_to_me&with_labels_details=true&search=${param}&per_page=7`,
    ISSUES_SEARCH_OPENED: (param) => `api/v4/issues?state=opened&scope=assigned_to_me&with_labels_details=true&search=${param}&per_page=7`,
    ISSUES_SEARCH_CLOSED: (param) => `api/v4/issues?state=closed&scope=assigned_to_me&with_labels_details=true&search=${param}&per_page=7`,

    ISSUE_STATE: (projectID, issueID, state) => `api/v4/projects/${projectID}/issues/${issueID}?state_event=${state}`,
    DELETE_ISSUE_NOTE: (projectID, issueID, noteID) => `api/v4/projects/${projectID}/issues/${issueID}/notes/${noteID}`,
    CREATE_ISSUE_NOTE: (projectID, issueID, body) => `api/v4/projects/${projectID}/issues/${issueID}/notes?body=${body}`,
    ISSUE_NOTES_SORTED: (projectID, issueID) => `api/v4/projects/${projectID}/issues/${issueID}/notes?sort=asc&order_by=updated_at`,

    DELETE_MERGE_REQUEST_NOTE: (projectID, mergeRequestID, noteID) => `api/v4/projects/${projectID}/merge_requests/${mergeRequestID}/notes/${noteID}`,
    CREATE_MERGE_REQUEST_NOTE: (projectID, mergeRequestID, body) => `api/v4/projects/${projectID}/merge_requests/${mergeRequestID}/notes?body=${body}`,
    MERGE_REQUEST_NOTES_SORTED: (projectID, mergeRequestID) => `api/v4/projects/${projectID}/merge_requests/${mergeRequestID}/notes?sort=asc&order_by=updated_at`,

    WEBHOOKS: (projectID) =>`api/v4/projects/${projectID}/hooks`
};
